"""Authentication constants."""

MIN_PASSWORD_LENGTH = 12
MAX_PASSWORD_LENGTH = 128

DEFAULT_JWT_ALGORITHM = "HS256"
DEFAULT_ACCESS_TOKEN_EXPIRE_MINUTES = 15
DEFAULT_REFRESH_TOKEN_EXPIRE_DAYS = 30

DEFAULT_EMAIL_VERIFICATION_EXPIRE_HOURS = 24
DEFAULT_PASSWORD_RESET_EXPIRE_MINUTES = 60

# Bytes of randomness per single-use token. secrets.token_urlsafe(32) yields a
# 256-bit token; its sha256 hex digest is 64 characters.
TOKEN_ENTROPY_BYTES = 32
TOKEN_HASH_LENGTH = 64
