# TODO: Implement Next.js Dockerfile when apps/web is built.

FROM node:20-alpine

WORKDIR /app

# TODO: Copy workspace files and install with pnpm
# TODO: Set CMD to run next start

CMD ["echo", "TODO: Implement web Dockerfile"]
