# TODO: Implement Celery worker Dockerfile when apps/worker is built.

FROM python:3.13-slim

WORKDIR /app

# TODO: Copy workspace files and install with uv
# TODO: Set CMD to run celery worker

CMD ["echo", "TODO: Implement worker Dockerfile"]
